# Generated by Django 3.2.12 on 2023-01-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gallery_name', models.CharField(max_length=100)),
                ('photo_1', models.ImageField(upload_to='wed_img/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='wed_img/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='wed_img/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='wed_img/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='wed_img/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='wed_img/%Y/%m/%d/')),
                ('photo_7', models.ImageField(blank=True, upload_to='wed_img/%Y/%m/%d/')),
                ('photo_8', models.ImageField(blank=True, upload_to='wed_img/%Y/%m/%d/')),
                ('photo_9', models.ImageField(blank=True, upload_to='wed_img/%Y/%m/%d/')),
                ('photo_10', models.ImageField(blank=True, upload_to='wed_img/%Y/%m/%d/')),
                ('photo_11', models.ImageField(blank=True, upload_to='wed_img/%Y/%m/%d/')),
                ('photo_12', models.ImageField(blank=True, upload_to='wed_img/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_meet_date', models.DateField()),
                ('Describe_first_meet', models.TextField()),
                ('Image_of_first_meet', models.ImageField(upload_to='wed_img/%Y/%m/%d')),
                ('First_date', models.DateField()),
                ('Describe_first_date', models.TextField()),
                ('Image_of_first_date', models.ImageField(upload_to='wed_img/%Y/%m/%d')),
                ('Relationship_date', models.DateField()),
                ('Say_something_about_Relationship', models.TextField()),
                ('Image_after_in_a_Relationship', models.ImageField(upload_to='wed_img/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_bride', models.CharField(max_length=100)),
                ('name_of_groom', models.CharField(max_length=100)),
                ('address_of_bride', models.CharField(max_length=100)),
                ('place_of_bride', models.CharField(max_length=100)),
                ('address_of_groom', models.CharField(max_length=100)),
                ('place_of_groom', models.CharField(max_length=100)),
                ('wedding_place_address', models.CharField(max_length=100)),
                ('wedding_place', models.CharField(max_length=100)),
                ('Wedding_quote', models.TextField()),
                ('image_bride', models.ImageField(upload_to='wed_img/%Y/%m/%d')),
                ('image_groom', models.ImageField(upload_to='wed_img/%Y/%m/%d')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='wedding_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceremony_from_time', models.TimeField()),
                ('ceremony_to_time', models.TimeField()),
                ('date_ceremony', models.DateField()),
                ('desc_ceremony', models.TextField()),
                ('party_from_time', models.TimeField()),
                ('party_to_time', models.TimeField()),
                ('date_party', models.DateField()),
                ('desc_party', models.TextField()),
            ],
        ),
    ]
