# Generated by Django 3.2.12 on 2023-01-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventpgm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wedding',
            old_name='date',
            new_name='wedding_date',
        ),
    ]
